# docker-compose.yml

version: '3.9'
services:

  postgres:
    container_name: books-directory-postgresql
    image: postgres:15-bullseye
    restart: unless-stopped
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: